name: UI
run-name: ${{ github.workflow }}; Trigger ${{ github.ref_name }}; Runner ${{ github.actor }}
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - ./**/*.json
      - .stylelintrc.js
      - .stylelintignore
      - .eslintignore
      - .gitignore
      - .prettierignore
      - README.md
      - yarn.lock
      - config/**/*
      - webpack.config.ts
jobs:
  chromatic:
    name: UI Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/prepare

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
